name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no aakashdhakal@aakashdhakal.com.np << 'EOF'
            cd /var/www/sangeet.aakashdhakal.com.np
            git pull origin main
            # Add any additional deployment commands here
          EOF
